import { FormData } from "@/app/page"

export const sampleData: FormData = {
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    phone: "(555) 123-4567",
    address_line: "123 Main St, Anytown, USA",
    dob: "1985-06-15",
    height_ft_in: "5'10\"",
    weight_lbs: "180",
    ssn: "123-45-6789",
    has_drivers_license: "yes",
    drivers_license_upload: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
    born_in_usa: "yes",
    state_of_birth: "California",
    passport_upload: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
    has_valid_visa: "N/A",
    visa_type: "",
    visa_expiration_date: "",
    has_green_card: "N/A",
    green_card_upload: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
    household_income: "100000",
    household_members: "4",
    occupation: "Software Engineer",
    employer_name: "Tech Corp",
    time_worked: "5 years",
    monthly_salary_usd: "8000",
    assets_description: "House, Car, Savings",
    has_business: "no",
    business_name: "",
    business_address: "",
    bank_name: "Chase",
    routing_number: "123456789",
    account_number: "987654321",
    account_type: "Checking",
    best_day_to_debit: "15th",
    has_current_life_insurance: "no",
    is_replacement: "no",
    ins_company_name: "",
    policy_number: "",
    coverage_amount_usd: "500000",
    visited_doctor_us: "yes",
    last_visit_date: "2024-01-10",
    doctor_name: "Dr. Smith",
    doctor_phone: "(555) 987-6543",
    visit_reason: "Annual Checkup",
    visit_result: "All good",
    has_preexisting_disease: "no",
    pre_existing_conditions: [],
    recent_weight_change: "no",
    weight_change_reason: "",
    used_nicotine_5y: "no",
    nicotine_product_type: "",
    qty_per_day: "",
    last_use_date: "",
    insurance_declined_history: "no",
    driving_violations: "no",
    criminal_record: "no",
    bankruptcy_involved: "no",
    pending_life_di_claim_12m: "no",
    work_disability_5y: "no",
    hazard_activities: "no",
    hazard_details: "",
    non_passenger_aviation: "no",
    aviation_details: "",
    cardio: "no",
    details_cardio: "",
    respiratory: "no",
    details_respiratory: "",
    digestive: "no",
    details_digestive: "",
    neuro: "no",
    details_neuro: "",
    endocrine: "no",
    details_endocrine: "",
    msk_skin: "no",
    details_msk_skin: "",
    urinary_repro: "no",
    details_urinary_repro: "",
    mental: "no",
    details_mental: "",
    onco_hema: "no",
    details_onco_hema: "",
    hiv: "no",
    details_hiv: "",
    alcohol_drugs: "no",
    details_alcohol_drugs: "",
    medications_current: "None",
    extra_doctors_5y: "no",
    details_extra_doctors_5y: "",
    hospitalized_5y_or_planned: "no",
    details_hospitalized_5y_or_planned: "",
    pending_appointments: "no",
    details_pending_appointments: "",
    father_alive: "yes",
    father_current_age: "70",
    father_dod: "",
    father_cause: "",
    mother_alive: "yes",
    mother_current_age: "68",
    mother_dod: "",
    mother_cause: "",
    family_history_major: "no",
    details_family_history_major: "",
    beneficiaries: [
        {
            beneficiary_full_name: "Jane Doe",
            beneficiary_dob: "1988-03-20",
            beneficiary_relation: "Spouse",
            beneficiary_relation_other: "",
            beneficiary_percentage: "100",
            beneficiary_address: "123 Main St",
            beneficiary_email: "jane@example.com",
            beneficiary_phone: "555-555-5555",
            beneficiary_ssn: "987-65-4321",
        },
    ],
    contingent_beneficiaries: [],
    agreement: true,
    signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==", // 1x1 pixel transparent png
    consent: true,
}
